spring:
  h2:
    console:
      enabled: true
      path: /h2-console

graphql:
  servlet:
    # (Optional) default: true
    enabled: true
    # (Optional) default: true
    corsEnabled: true
    # (Optional) default: /graphql
    mapping: /graphql

graphiql:
  # (Optional) default: true
  enabled: true
  # (Optional) default: /graphql
  endpoint: /graphql
  # (Optional) default: /graphiql
  mapping: /graphiql
