spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:h2:mem:/graphql-spring-boot-sample
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

graphql:
  servlet:
    # (Optional) default: true
    enabled: true
    # (Optional) default: true
    corsEnabled: true
    # (Optional) default: /graphql
    # Context path complete this.
    mapping: /graphql

graphiql:
  # (Optional) default: true
  enabled: true
  # (Optional) default: /graphql
  # Context path DON'T complete this.
  # e.g. ${server.context-path}${graphql.servlet.mapping}
  endpoint: /graphql
  # (Optional) default: /graphiql
  # Context path complete this.
  mapping: /graphiql
