spring:
  h2:
    console:
      enabled: true
      path: /h2-console

graphql:
  servlet:
    enabled: true
    mapping: /graphql
    corsEnabled: true

graphiql:
  enabled: true
  mapping: /graphiql
  endpoint: /graphql

